### ISSUE TITLE
Orange screen on boot

### ISSUE THREAD

**Issue by fonix232** [ayufan-pine64/android-7.1#1]
Some of us experienced immediate orange screen upon booting.

The device boots up fine, available through network, but the display stays orange. Everything else seems to be okay. Changing the HDMI mode does not alter the outcome, nor does the presence of the WiFi module.

**Hardware:** Pine A64+ 2GB
**Storage:** Samsung EVO+ 32GB / Transcend Ultra 16GB
**Display:** Philips 43PUH4900/88

**Confirmed last working release:** Android TV 6.0 v1.0.1 r20
**Releases with issue present:**

- 6.0 v1.1.3 r26
- 7.0 v1.12.5 r73
- 7.1 v0.2.3 r9

If required I can open the same issue on all three repos, so that tracking is possible.

**Comment by rluncasu** [comment]
Same here, similar setup as @fonix232 with a LG 42LV375S hdmi display

**Comment by tuluse** [comment]
I have the same problem with all the pre-release versions I've tried. The release versions seem to work fine.

**Comment by kenjiru** [comment]
I have the same problem. It would be nice to have this fixed..

**Comment by Airtau** [comment]
I have the same problem.
**Hardware:** Pine A64+ 2GB
**Display:**  Samsung  T260HD

1|tulip-chiphd:/ # dmesg |grep hdmi
[   10.936010] hdmi-set_default_source=pll_video0 success!
[   13.693297] sndhdmi sound.7:  sndhdmi <-> 1c22800.daudio mapping ok
[   14.055304]   #2: sndhdmi
[   18.475757] [HDMI] power vcc-hdmi-33
[   19.472217] hdmi_clk_enable_prepare()L181
[   26.697672] hdmi_clk_disable_prepare()L196
[   26.812860] hdmi_clk_enable_prepare()L181
[   26.817284] hdmi_clk_disable_prepare()L196
[   26.930987] hdmi_clk_enable_prepare()L181
[   26.935402] hdmi_clk_disable_prepare()L196
[   27.058877] hdmi_clk_enable_prepare()L181
[   27.063291] hdmi_clk_disable_prepare()L196
[   27.176950] hdmi_clk_enable_prepare()L181
[   27.181359] hdmi_clk_disable_prepare()L196
[   27.295042] hdmi_clk_enable_prepare()L181
[   27.299455] hdmi_clk_disable_prepare()L196
[   27.413110] hdmi_clk_enable_prepare()L181
[   27.417523] hdmi_clk_disable_prepare()L196
[   27.531201] hdmi_clk_enable_prepare()L181
[   27.535622] hdmi_clk_disable_prepare()L196
[   27.855904] hdmi_clk_enable_prepare()L181
[   27.860340] hdmi_clk_disable_prepare()L196
[   27.865953] [HDMI WRN] file:/android/linux/kernel-tulip/drivers/video/sunxi/disp2/hdmi/drv_hdmi.c,line:351:    unsupported video mode 11 when set display mode
[   28.180640] hdmi_clk_enable_prepare()L181
[   28.185081] hdmi_clk_disable_prepare()L196
[   28.190461] [HDMI WRN] file:/android/linux/kernel-tulip/drivers/video/sunxi/disp2/hdmi/drv_hdmi.c,line:351:    unsupported video mode 14 when set display mode
[   28.515242] hdmi_clk_enable_prepare()L181
[   52.102622] type=1400 audit(1262307302.210:47): avc: denied { read write } for pid=2553 comm="system_server" name="sunxi_hdmi_cec" dev="tmpfs" ino=7258 scontext=u:r:system_server:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
[   52.129019] HDMI hdmi_cec_thread started
[   52.131081] type=1400 audit(1262307302.220:48): avc: denied { open } for pid=2553 comm="system_server" path="/dev/sunxi_hdmi_cec" dev="tmpfs" ino=7258 scontext=u:r:system_server:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
[   52.131239] type=1400 audit(1262307302.220:49): avc: denied { ioctl } for pid=2553 comm="system_server" path="/dev/sunxi_hdmi_cec" dev="tmpfs" ino=7258 scontext=u:r:system_server:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
[   52.229732] hdmi_cec_finish_send: buf=44 00 00 00 msg_len=1 tx_answer=CEC_TX_NACK
[   52.308331] hdmi_cec_finish_send: buf=44 00 00 00 msg_len=1 tx_answer=CEC_TX_NACK
[   52.347858] hdmi_cec_finish_send: buf=44 00 00 00 msg_len=1 tx_answer=CEC_TX_NACK
[   57.189138] hdmi_cec_finish_send: buf=4f 84 10 00 msg_len=5 tx_answer=CEC_TX_DONE
[   57.326862] hdmi_cec_finish_send: buf=4f 87 00 15 msg_len=5 tx_answer=CEC_TX_DONE

**Comment by Metalheadx1982** [comment]
I also have the same issue. I have tested it on 6 monitors with hdmi to vga, hdmi to hdmi, hdmi to dvi and have also tested on 5 different model HD TV's all the way from a 60" Plasma down to 55 rear projection  LCD's 4k down to 480P . I cannot get any visuals after the Orange screen's on boot. Looks like its trying to figure out what resolution to keep, the orange screen starts at 720 then flashes to 1080 than blank. Hoping we can see a patch or something soon.

**Comment by stolendata** [comment]
Same problem on my 1GB Pine64+ (A64-DB-Rev B board) when trying the tv-v0.2.5-r13 build. At first I thought it might be either the presence of my WiFi/BT module or the LCD/HDMI/CEC settings in the uEnv.txt config file, but after playing around with combinations I can safely say that this release will not boot on my Pine64.

Boot output captured from serial port: https://pastebin.com/raw/yypNc4F3

**Comment by ayufan** [comment]
It should be OK in latest build.

**Comment by stolendata** [comment]
**android-7.1-pine-a64-v0.3.5-r61**

Still does not properly boot on a 1GB Pine 64+. No orange screen in this build, but after the Google boot animation starts playing the Pine powers down just 3-4 seconds later.

**Comment by ayufan** [comment]
I need uart log.

**Comment by stolendata** [comment]
https://transfer.sh/132cry/logs.tar.gz

These logs show as far as it gets at most. The behavior is random from boot to boot, and for some reason it seems to do better when I'm pulling data from the UART. When it's disconnected, the Pine64 will power off early; when UART is connected, it lasts for about 60 seconds, until it tries to start up 'netd'.
