### ISSUE TITLE
Missing apps from TV Launcher

### ISSUE THREAD

**Issue by snagytx** [ayufan-pine64/android-7.1#11]
I'm using Android 7.1 TV ver 0.3.5 build 61 - I had a clean install from the img file.

Not sure if it's just me or it's a general issue but if I install Chrome( by going to https://play.google.com/store) OR installing "Ace Browser" - directly on from the store on the device OR Sideload Netflix using ES File Explorer, I can see that the app is installed and they all work but once is installed I don't see it in the TV App Lancher. If I Check in the Settings I see the apps installed, If I check ES File Explorer I see the apps installed, if I install a third party launcher I can see the apps - the issue is with the default app launcher.

Is this specific to the build or to my environment?

**Comment by ayufan** [comment]
It is correct. You will only see TV apps, not a regular one. To run regular ones use https://play.google.com/store/apps/details?id=eu.chainfire.tv.sideloadlauncher&hl=en.
