### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by mikeygao** [ayufan-pine64/android-7.1#2]
ninja: error: 'out/target/common/obj/APPS/BasicDreams_intermediates/with-local/classes.dex', needed by 'out/target/common/obj/APPS/BasicDreams_intermediates/classes.dex', missing and no known rule to make it

I used OpenJDK 8.0 as requested when begin to build by environment checking.
ANDROID_COMPILE_WITH_JACK=false

**Comment by ayufan** [comment]
Interesting. Take a look at my build where it did succeed recently: https://jenkins.ayufan.eu/job/android-7.1-pine-a64/9/console.

**Comment by mikeygao** [comment]
Use Jack and build successfully. But 
pine64_android_7_1.img: unrecognized partition table type

**Comment by mikeygao** [comment]
after upgrade sfdisk to 2.28.1, create image successfully.
