### ISSUE TITLE
No audio over HDMI

### ISSUE THREAD

**Issue by avanderbergh** [ayufan-pine64/android-7.1#5]
I don't get any audio out over HDMI on my LG TV. Audio works fine in my Android 5 build, but no audio on 6.0, 7.0 or 7.1

[See this issue on 6.0
](https://github.com/ayufan-pine64/android-6.0/issues/5)

**Comment by matanporeh** [comment]
same issue for me here with LG TV as well - android 5.1 sound worked - but android 7/6 don't

**Comment by Flipez** [comment]
Same here. Working on 5 but not on 7. Also with an LG TV

**Comment by matanporeh** [comment]
why isn't anybody from the team answering these comments? at least to let us know they know of the issue. very disappointing

**Comment by ayufan** [comment]
This is community maintained build, done on best-effort without any
guarantees and it is not stated that everything has to work in every
possible configuration.

As with every community, we welcome any improvements that could help others
:)

**Comment by Flipez** [comment]
@ayufan Do you have any idea why this does not work with android 7 ? Is this due to the LG TVs? Does anybody run Android TV 7.1 with audio over hdmi successfully?

**Comment by alternativ** [comment]
I have it working on a Samsung, did switch off the surround toggle in sound settings.

**Comment by avanderbergh** [comment]
It works! I booted the Pine64 without the Pine 64 Air Mouse connected and the sound works. The Air Mouse has a built-in microphone, so it seems that Android wants to use that as the default sound device.

**Comment by mircobocedi** [comment]
@ayufan 
There is a problem in kernel drivers loading sequence. If u launch dmesg command from console u can see that Airmouse audio is listed as first Alsa card.

I don't know why, but if i put loglevel=2 instead of loglevel=8 as kernel bootargs in boot.cmd on the first partitition of the image and i re-generate  boot.scr, the problem disappear. 

i hope this trick can be useful!

**Comment by TaylorBruce** [comment]
@microbocedi could you describe how you made those changes to enable sound over HDMI please?

**Comment by karimsj** [comment]
> @microbocedi could you describe how you made those changes to enable sound over HDMI please?

You can change the default audio output by making changes in /etc/audio_policy.conf file

For enabling default HDMI audio output > AUDIO_DEVICE_OUT_AUX_DIGITAL
For 3.5 mm > AUDIO_DEVICE_OUT_WIRED_HEADPHONE

```
global_configuration {
  attached_output_devices AUDIO_DEVICE_OUT_EARPIECE|AUDIO_DEVICE_OUT_SPEAKER|AUDIO_DEVICE_OUT_WIRED_HEADPHONE|AUDIO_DEVICE_OUT_AUX_DIGITAL
  default_output_device AUDIO_DEVICE_OUT_AUX_DIGITAL
  attached_input_devices AUDIO_DEVICE_IN_BUILTIN_MIC|AUDIO_DEVICE_IN_BACK_MIC|AUDIO_DEVICE_IN_VOICE_CALL|AUDIO_DEVICE_IN_REMOTE_SUBMIX
}
```

**Comment by mircobocedi** [comment]
> > @microbocedi could you describe how you made those changes to enable sound over HDMI please?
> 
> You can change the default audio output by making changes in /etc/audio_policy.conf file
> 
> For enabling default HDMI audio output > AUDIO_DEVICE_OUT_AUX_DIGITAL
> For 3.5 mm > AUDIO_DEVICE_OUT_WIRED_HEADPHONE
> 
> ```
> global_configuration {
>   attached_output_devices AUDIO_DEVICE_OUT_EARPIECE|AUDIO_DEVICE_OUT_SPEAKER|AUDIO_DEVICE_OUT_WIRED_HEADPHONE|AUDIO_DEVICE_OUT_AUX_DIGITAL
>   default_output_device AUDIO_DEVICE_OUT_AUX_DIGITAL
>   attached_input_devices AUDIO_DEVICE_IN_BUILTIN_MIC|AUDIO_DEVICE_IN_BACK_MIC|AUDIO_DEVICE_IN_VOICE_CALL|AUDIO_DEVICE_IN_REMOTE_SUBMIX
> }
> ```

this method is not working...
