### ISSUE TITLE
No ethernet setting on Android-non-tv, bug or feature?

### ISSUE THREAD

**Issue by DrCroubie** [ayufan-pine64/android-7.1#7]
I've tried burning the latest android-7.1-pine-a64-tv-v0.3.5-r61.img, and networking works fine.
But this 'tv' version it's really clunky and weird to use: the home screen is weird and I can't put app shortcuts on it; I have to go to settings->apps to start anything that's not on there by default; I can't get rid of that recommendations app nor that microphone thing.
But more importantly, the Stan app just crashes on boot, and Stan all I want to use this thing for.

So I tried installing just the non-tv android-7.1-pine-a64-v0.3.5-r61.img
Much better, looks a lot more like the Android that I know and <at least know how to use>. But there's no setting for wired ethernet? According to https://forum.pine64.org/showthread.php?tid=4416&pid=27187#pid27187, "You have to dig a little deeper in the menus to find Ethernet setup, but it is there." (I tried replying on the forums, but can't write anything for 3 days, so much for swift support).

Anyway, is it there? Where? I've looked in every menu that I can find under settings, no ethernet, just wifi and bluetooth. Is there a special way to get to the ethernet settings on Android non-tv? Or is there just not meant to be any ethernet by design, and wired-ethernet is forced to use that weird ugly tv version?

**Comment by DrCroubie** [comment]
ps, I just checked, and ethernet does exist and work on the older android-ver6.0-20170112-pine64-64GB.img. So is it just not present on 7.1, or not implemented yet?

**Comment by ayufan** [comment]
Sorry, I'm not releasing AW based changes, only pure clean AOSP. The version to what you are referencing is AW version. My version you can find https://github.com/ayufan-pine64/android-6.0/releases. I don't plan to support that function.

**Comment by DrCroubie** [comment]
Hi, I'm not up with abbreviations, AW=?, AOSP=?
Do I understand correctly that you're saying Android 6 does supprt wired ethernet, but Android 7 doesn't and won't?

**Comment by ayufan** [comment]
AW => allwinner android
AOSP => android open source project

Both do support, AW does expose some extra ethernet settings, but this is not part of AOSP. I do distribute only AOSP.
